[package]
name = "sawtooth_oscillator"
version = "0.1.0"
authors = ["Charles Saracco <crsaracco@gmail.com>"]

[dependencies]
vst2 = { git = "https://github.com/rust-dsp/rust-vst" }

[lib]
name = "sawtooth_oscillator"
crate-type = ["dylib"]